# Generated by Django 2.2.18 on 2021-02-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
