# Generated by Django 2.2.18 on 2021-02-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_test_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test2_test', to='home.Test'),
        ),
    ]
